### ISSUE TITLE
conf.d file handling

### ISSUE THREAD

**Issue by mattmc3** [kidonng/fisher_path.fish#1]
This line seems problematic:

https://github.com/kidonng/fisher_path.fish/blob/fc6037737cf155165ba754bdbc981aab4a302fe9/conf.d/fisher_path.fish#L12

Essentially, if you have a file in your `~/.config/fish/conf.d` that happens to have the same name as a file in a plugin's conf.d, the plugin's file is skipped in favor of yours. This kind of logic makes sense for functions where you want to override the function in your own config, but if you want to override some conf.d settings for a plugin you likely wouldn't want to do it this way.

It seems much more likely that you'll wind up with an unintentionally broken plugin because of an accidental name collision.

Imagine using the Hydro prompt and you have the following scenario:
- Plugin file: https://github.com/jorgebucaran/hydro/blob/main/conf.d/hydro.fish
- Your conf.d/hydro.fish
```fish
if test "$hydro_prompt_initialized" != true
    set -g hydro_prompt_initialized true
    set -g hydro_symbol_prompt "»"
    set -g hydro_symbol_git_dirty "*"
    set -g hydro_symbol_git_ahead "⇡"
    set -g hydro_symbol_git_behind "⇣"

    set -g hydro_color_git green
    set -g hydro_color_prompt cyan
    set -g hydro_color_pwd blue
    set -g hydro_color_error red
    set -g hydro_multiline true
end
```

It would be really confusing why your Hydro file stopped the Hydro plugin from working.

**Comment by kidonng** [comment]
> Essentially, if you have a file in your `~/.config/fish/conf.d` that happens to have the same name as a file in a plugin's conf.d, the plugin's file is skipped in favor of yours.

Right, that's [how fish's configuration files works](https://fishshell.com/docs/current/#configuration-files).

> This kind of logic makes sense for functions where you want to override the function in your own config, but if you want to override some conf.d settings for a plugin you likely wouldn't want to do it this way.

The files in `~/.config/fish` should always have the highest priority. It would only be more confusing if some of them are respected but some aren't.

> It seems much more likely that you'll wind up with an unintentionally broken plugin because of an accidental name collision.

That's valid though, because not many people are aware of this behavior. I will make it clear in the README.

> Imagine using the Hydro prompt and you have the following scenario:
> - Plugin file: https://github.com/jorgebucaran/hydro/blob/main/conf.d/hydro.fish
> - Your conf.d/hydro.fish
> It would be really confusing why your Hydro file stopped the Hydro plugin from working.

Here's my two cents: unlike `functions`and `completions`, you really should not put your config files in `conf.d`[^1]. Even if you can ensure they don't have name clash with any other files, you may still encounter issues caused by loading order. **Just use `config.fish` for your own config**. You can still use separate files if you want, source them in `config.fish` and you are good to go, theoretically it is even faster than putting them in `conf.d`.

And `conf.d` should only be used for "masking", or overriding the entire `conf.d` script loaded elsewhere. For example, the way I installed fzf comes with its vendored fish key bindings, via a conf.d script. I prefer fzf.fish over it, so I just create a symlink to `/dev/null` with the name of the script, and put it into `conf.d`, mission accomplished. 

Remember that this is the only way to ensure _you_ are in control, not the plugins.

[^1]: Need to clarify a bit: this is when you are using plugins. If you don't use any then feel free to use `conf.d` as you like.
